import { FilterOperator, FilterSuffix, PaginateConfig } from 'nestjs-paginate';
import { Invoice } from './entities/invoice.entity';

export const paginateConfig: PaginateConfig<Invoice> = {
  relations: ['client'],
  sortableColumns: [
    'id',
    'createdAt',
    'dueDate',
    'paymentMadeOn',
    'amountWithVat',
    'amountWithoutVat',
    'vat',
  ],
  nullSort: 'last',
  defaultSortBy: [['createdAt', 'DESC']],
  searchableColumns: [
    'id',
    'invoiceNumber',
    'createdAt',
    'paymentType',
    'category',
    'client',
    'notes',
    'currency',
    'amountWithVat',
    'amountWithoutVat',
    'vat',
    'dueDate',
    'paymentMadeOn',
    'paymentMethod',
  ],
  select: [
    'id',
    'invoiceNumber',
    'createdAt',
    'paymentType',
    'category',
    'client.name',
    'client.id',
    'notes',
    'currency',
    'amountWithVat',
    'amountWithoutVat',
    'vat',
    'dueDate',
    'paymentMadeOn',
    'paymentMethod',
  ],
  filterableColumns: {
    client: [FilterOperator.EQ, FilterSuffix.NOT],
    category: [FilterOperator.EQ, FilterSuffix.NOT],
    paymentType: [FilterOperator.EQ, FilterSuffix.NOT],
    paymentMethod: [FilterOperator.EQ, FilterSuffix.NOT],
  },
};
